This notebook will be used for the Coursera capstone project

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
# using pandas to read the html in dataframe dfs
dfs=pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')

In [3]:
len(dfs)

3

In [4]:
# read only the first table and store in another dataframe df
df=dfs[0]

In [5]:
# display the dataframe
df.head(15)

   Postcode           Borough     Neighbourhood
0       M1A      Not assigned      Not assigned
1       M2A      Not assigned      Not assigned
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
9       M8A      Not assigned      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern
13      M2B      Not assigned      Not assigned
14      M3B        North York   Don Mills North

In [6]:
# Drop the rows with Borough as "Not assigned"
mod_df=df[df.Borough !='Not assigned']
mod_df.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [7]:
# indetify Neighbourhood which is "No assigned"

filter = mod_df['Neighbourhood']=='Not assigned'
mod_df.where(filter).dropna()

  Postcode       Borough Neighbourhood
8      M7A  Queen's Park  Not assigned

In [8]:
# Replace the Neighourhood "Not assigned" with corresponding Borough, "Queen's Park" in this case
mod_df.replace(to_replace =["Not assigned"],  
                            value ="Queen's Park")

,Postcode,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Harbourfront
5,M5A,Downtown Toronto,Regent Park
6,M6A,North York,Lawrence Heights
7,M6A,North York,Lawrence Manor
8,M7A,Queen's Park,Queen's Park
10,M9A,Etobicoke,Islington Avenue
11,M1B,Scarborough,Rouge
12,M1B,Scarborough,Malvern
14,M3B,North York,Don Mills North
15,M4B,East York,Woodbine Gardens
16,M4B,East York,Parkview Hill
17,M5B,Downtown Toronto,Ryerson
18,M5B,Downtown Toronto,Garden District
19,M6B,North York,Glencairn
22,M9B,Etobicoke,Cloverdale
23,M9B,Etobicoke,Islington
24,M9B,Etobicoke,Martin Grove
25,M9B,Etobicoke,Princess Gardens
26,M9B,Etobicoke,West Deane Park
27,M1C,Scarborough,Highland Creek
28,M1C,Scarborough,Rouge Hill
29,M1C,Scarborough,Port Union
31,M3C,North York,Flemingdon Park
32,M3C,North York,Don Mills South
33,M4C,East York,Woodbine Heights
34,M5C,Downtown Toronto,St. James Town
35,M6C,York,Humewood-Cedarvale
38,M9C,Etobicoke,Bloordale Gardens
...,...,...,...
235,M9V,Etobicoke,Thistletown
236,M1W,Scarborough,L'Amoreaux West
239,M4W,Downtown Toronto,Rosedale
240,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade
243,M8W,Etobicoke,Alderwood
244,M8W,Etobicoke,Long Branch
245,M9W,Etobicoke,Northwest
246,M1X,Scarborough,Upper Rouge
249,M4X,Downtown Toronto,Cabbagetown
250,M4X,Downtown Toronto,St. James Town
251,M5X,Downtown Toronto,First Canadian Place
252,M5X,Downtown Toronto,Underground city
255,M8X,Etobicoke,The Kingsway
256,M8X,Etobicoke,Montgomery Road
257,M8X,Etobicoke,Old Mill North
262,M4Y,Downtown Toronto,Church and Wellesley
265,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
266,M8Y,Etobicoke,Humber Bay
267,M8Y,Etobicoke,King's Mill Park
268,M8Y,Etobicoke,Kingsway Park South East
269,M8Y,Etobicoke,Mimico NE
270,M8Y,Etobicoke,Old Mill South
271,M8Y,Etobicoke,The Queensway East
272,M8Y,Etobicoke,Royal York South East
273,M8Y,Etobicoke,Sunnylea
282,M8Z,Etobicoke,Kingsway Park South West
283,M8Z,Etobicoke,Mimico NW
284,M8Z,Etobicoke,The Queensway West
285,M8Z,Etobicoke,Royal York South West
286,M8Z,Etobicoke,South of Bloor

In [15]:
# Now group the dataframe by Postcode and store in dataframe called final_df
final_df=mod_df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(', '.join).reset_index()
final_df.head(50)

,Postcode,Borough,Neighbourhood
0,M1B,Scarborough,"Rouge, Malvern"
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park"
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge"
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff, Cliffside West"
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ..."
11,M1R,Scarborough,"Maryvale, Wexford"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter"
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St..."
15,M1W,Scarborough,L'Amoreaux West
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview, Henry Farm, Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"Silver Hills, York Mills"
21,M2M,North York,"Newtonbrook, Willowdale"
22,M2N,North York,Willowdale South
23,M2P,North York,York Mills West
24,M2R,North York,Willowdale West
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills North
27,M3C,North York,"Flemingdon Park, Don Mills South"
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights"
29,M3J,North York,"Northwood Park, York University"
30,M3K,North York,"CFB Toronto, Downsview East"
31,M3L,North York,Downsview West
32,M3M,North York,Downsview Central
33,M3N,North York,Downsview Northwest
34,M4A,North York,Victoria Village
35,M4B,East York,"Woodbine Gardens, Parkview Hill"
36,M4C,East York,Woodbine Heights
37,M4E,East Toronto,The Beaches
38,M4G,East York,Leaside
39,M4H,East York,Thorncliffe Park
40,M4J,East York,East Toronto
41,M4K,East Toronto,"The Danforth West, Riverdale"
42,M4L,East Toronto,"The Beaches West, India Bazaar"
43,M4M,East Toronto,Studio District
44,M4N,Central Toronto,Lawrence Park
45,M4P,Central Toronto,Davisville North
46,M4R,Central Toronto,North Toronto West
47,M4S,Central Toronto,Davisville
48,M4T,Central Toronto,"Moore Park, Summerhill East"
49,M4V,Central Toronto,"Deer Park, Forest Hill SE, Rathnelly, South Hi..."

In [10]:
final_df.loc[final_df['Postcode'] == 'M5A']

   Postcode           Borough              Neighbourhood
53      M5A  Downtown Toronto  Harbourfront, Regent Park

In [11]:
#Displace the size of final dataframe
final_df.shape

(103, 3)

In [17]:
geodata=pd.read_csv('http://cocl.us/Geospatial_data')
geodata.head(50)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750072 -79.295849
12         M1S  43.794200 -79.262029
13         M1T  43.781638 -79.304302
14         M1V  43.815252 -79.284577
15         M1W  43.799525 -79.318389
16         M1X  43.836125 -79.205636
17         M2H  43.803762 -79.363452
18         M2J  43.778517 -79.346556
19         M2K  43.786947 -79.385975
20         M2L  43.757490 -79.374714
21         M2M  43.789053 -79.408493
22         M2N  43.770120 -79.408493
23         M2P  43.752758 -79.400049
24         M2R  43.782736 -79.442259
25         M3A  43.753259 -79.329656
26         M3B  43.745906 -79.352188
27         M3C  43.725900 -79.340923
28         M3H  43.754328 -79.442259
29         M3J  43.767980 -79.487262
30         M3K  43.737473 -79.464763
31         M3L  43.739015 -79.506944
32         M3M  43.728496 -79.495697
33         M3N  43.761631 -79.520999
34         M4A  43.725882 -79.315572
35         M4B  43.706397 -79.309937
36         M4C  43.695344 -79.318389
37         M4E  43.676357 -79.293031
38         M4G  43.709060 -79.363452
39         M4H  43.705369 -79.349372
40         M4J  43.685347 -79.338106
41         M4K  43.679557 -79.352188
42         M4L  43.668999 -79.315572
43         M4M  43.659526 -79.340923
44         M4N  43.728020 -79.388790
45         M4P  43.712751 -79.390197
46         M4R  43.715383 -79.405678
47         M4S  43.704324 -79.388790
48         M4T  43.689574 -79.383160
49         M4V  43.686412 -79.400049

In [20]:
final_df['Latitude']=geodata['Latitude']
final_df['Longitude']=geodata['Longitude']
final_df.head(5)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476